### ISSUE TITLE
Lua Errors: Calling net.Start with unpooled message name! [http://goo.gl/qcx0y]

### ISSUE THREAD

**Issue by AMD-NICK** [LuaTenshi/GLua#7]
**1**
L 07/23/2015 - 18:49:32: OlegKruto|52RUS (STEAM_0:1:63xxx725) Attempted to use tool creator
L 07/23/2015 - 18:49:32: OlegKruto|52RUS (STEAM_0:1:63xxx725) Spawned a models/props_c17/furnitureStove001a.mdl
L 07/23/2015 - 18:49:32: Lua Error: 
[ERROR] addons/apanti/lua/autorun/server/sv_apanti.lua:312: Calling net.Start with unpooled message name! [http://goo.gl/qcx0y]
  1. Start - [C]:-1
   2. DMsg - addons/apanti/lua/autorun/server/sv_apanti.lua:312
    3. fn - addons/apanti/lua/autorun/server/sv_apanti.lua:473
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:

**2**
L 07/23/2015 - 19:56:56: didosha (STEAM_0:0:59xxx892) Attempted to use tool rope
L 07/23/2015 - 19:56:56: Lua Error: 
[ERROR] addons/apanti/lua/autorun/server/sv_apanti.lua:312: Calling net.Start with unpooled message name! [http://goo.gl/qcx0y]
  1. Start - [C]:-1
   2. DMsg - addons/apanti/lua/autorun/server/sv_apanti.lua:312
    3. fn - addons/apanti/lua/autorun/server/sv_apanti.lua:473
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

**3**
Desire<STEAM_0:0:66xxx341> spawned model models/props/cs_office/sofa.mdl
L 07/23/2015 - 21:01:02: Lua Error: 
[ERROR] addons/apanti/lua/autorun/server/sv_apanti.lua:312: Calling net.Start with unpooled message name! [http://goo.gl/qcx0y]
  1. Start - [C]:-1
   2. DMsg - addons/apanti/lua/autorun/server/sv_apanti.lua:312
    3. fn - addons/apanti/lua/autorun/server/sv_apanti.lua:473
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

**Comment by LuaTenshi** [comment]
What exactly are you trying to do? Are you using the latest version?

**Comment by AMD-NICK** [comment]
> What exactly are you trying to do?
Nothing. And I do not know what players doing for calling this error

> Are you using the latest version?
Yes.

**Comment by LuaTenshi** [comment]
Alright, I found the issue. I will fix it when I'm at my computer as I can't do much from my phone.

**Comment by AMD-NICK** [comment]
So what about error? :)

**Comment by LuaTenshi** [comment]
This should now be fixed.
